parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Model\Shipping\Discount\Rule\RuleApplier:
        arguments:
            $globalRules:
                - '@App\Model\Shipping\Discount\Rule\Global\SmallCheapestProvider'
            $rulesToApply:
                - '@App\Model\Shipping\Discount\Rule\Current\LargeLP'

    App\Model\Shipping\Provider\ProviderRepository:
        arguments:
            $providers:
                - '@App\Model\Shipping\Provider\LaPoste'
                - '@App\Model\Shipping\Provider\MondialRelay'

    App\Service\Shipping\ValidationService:
        arguments:
            $dateValidator: '@App\Model\Shipping\Validator\Date'
            $packageSizeValidator: '@App\Model\Shipping\Validator\PackageSize'
            $carrierCodeValidator: '@App\Model\Shipping\Validator\CarrierCode'

